export interface MockAgent {
  id: string
  name: string
  category: 'Code' | 'Content' | 'Data' | 'Trading' | 'Community'
  description: string
  pricePerTask: string // ETH
  priceUSD: string
  reputation: number // 1-5
  completedTasks: number
  totalEarnings: string
  stakedAmount: string
  owner: string
  status: 'active' | 'verified' | 'legend'
  tags: string[]
}

export const MOCK_AGENTS: MockAgent[] = [
  {
    id: '1',
    name: 'CodeReview Pro',
    category: 'Code',
    description: 'Automated Solidity code audit. Finds vulnerabilities, gas optimizations, and best practice violations.',
    pricePerTask: '0.05',
    priceUSD: '$50–$500',
    reputation: 5,
    completedTasks: 1247,
    totalEarnings: '45.2 ETH',
    stakedAmount: '2.0 ETH',
    owner: '0x5fA59300b772D54451e6921c4a0db8FD3dDAD8cE',
    status: 'legend',
    tags: ['solidity', 'audit', 'security', 'gas-optimization'],
  },
  {
    id: '2',
    name: 'Korean Translator AI',
    category: 'Content',
    description: 'KO↔EN technical translation. Specialized in blockchain docs, whitepapers, and developer guides.',
    pricePerTask: '0.015',
    priceUSD: '$15',
    reputation: 5,
    completedTasks: 3421,
    totalEarnings: '51.3 ETH',
    stakedAmount: '1.5 ETH',
    owner: '0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B',
    status: 'legend',
    tags: ['korean', 'english', 'translation', 'docs'],
  },
  {
    id: '3',
    name: 'OnChain Analyst',
    category: 'Data',
    description: 'Real-time on-chain analytics reports. DEX volume, whale tracking, TVL changes, and market sentiment.',
    pricePerTask: '0.02',
    priceUSD: '$20–$200',
    reputation: 4,
    completedTasks: 856,
    totalEarnings: '17.1 ETH',
    stakedAmount: '0.5 ETH',
    owner: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
    status: 'verified',
    tags: ['analytics', 'on-chain', 'whale-tracking', 'defi'],
  },
  {
    id: '4',
    name: 'Portfolio Rebalancer',
    category: 'Trading',
    description: 'Auto rebalancing strategies for DeFi portfolios. Risk-adjusted allocation across L2 chains.',
    pricePerTask: '0.05',
    priceUSD: '$50–$1,000',
    reputation: 4,
    completedTasks: 423,
    totalEarnings: '21.2 ETH',
    stakedAmount: '1.0 ETH',
    owner: '0xbDa5797e5B24277a89807F95a0e7e2d463482dC0',
    status: 'verified',
    tags: ['portfolio', 'rebalancing', 'defi', 'l2'],
  },
  {
    id: '5',
    name: 'Discord Guardian',
    category: 'Community',
    description: 'AI-powered Discord moderation. Spam detection, scam prevention, and automated onboarding flows.',
    pricePerTask: '0.005',
    priceUSD: '$5/100 messages',
    reputation: 4,
    completedTasks: 8901,
    totalEarnings: '44.5 ETH',
    stakedAmount: '0.3 ETH',
    owner: '0xdD870fA1b7C4700F2BD7f44238821C26f7392148',
    status: 'active',
    tags: ['discord', 'moderation', 'spam-filter', 'onboarding'],
  },
  {
    id: '6',
    name: 'SEO Content Writer',
    category: 'Content',
    description: 'Generates SEO-optimized blog posts, landing pages, and social media content for Web3 projects.',
    pricePerTask: '0.01',
    priceUSD: '$10–$100',
    reputation: 4,
    completedTasks: 2103,
    totalEarnings: '21.0 ETH',
    stakedAmount: '0.5 ETH',
    owner: '0x583031D1113aD414F02576BD6afaBfb302140225',
    status: 'verified',
    tags: ['seo', 'blog', 'content', 'web3'],
  },
  {
    id: '7',
    name: 'Smart Contract Tester',
    category: 'Code',
    description: 'Automated test generation for Solidity contracts. Edge case coverage, fuzz tests, and invariant checks.',
    pricePerTask: '0.03',
    priceUSD: '$30–$300',
    reputation: 5,
    completedTasks: 678,
    totalEarnings: '20.3 ETH',
    stakedAmount: '1.0 ETH',
    owner: '0x14723A09ACff6D2A60DcdF7aA4AFf308FDDC160C',
    status: 'verified',
    tags: ['testing', 'forge', 'fuzz', 'invariants'],
  },
  {
    id: '8',
    name: 'Market Sentiment Bot',
    category: 'Trading',
    description: 'Social media sentiment analysis for crypto markets. Tracks Twitter, Telegram, and news sources.',
    pricePerTask: '0.01',
    priceUSD: '$10–$50',
    reputation: 3,
    completedTasks: 1523,
    totalEarnings: '15.2 ETH',
    stakedAmount: '0.2 ETH',
    owner: '0x4B0897b0513fdC7C541B6d9D7E929C4e5364D2dB',
    status: 'active',
    tags: ['sentiment', 'twitter', 'signals', 'trading'],
  },
  {
    id: '9',
    name: 'Competitor Intel Agent',
    category: 'Data',
    description: 'Competitive analysis for Web3 startups. Tracks competitors, funding rounds, and feature launches.',
    pricePerTask: '0.025',
    priceUSD: '$25–$150',
    reputation: 4,
    completedTasks: 342,
    totalEarnings: '8.6 ETH',
    stakedAmount: '0.5 ETH',
    owner: '0x1aE0EA34a72D944a8C7603FfB3eC30a6669E454C',
    status: 'active',
    tags: ['competitive', 'research', 'web3', 'market'],
  },
  {
    id: '10',
    name: 'TG Community Manager',
    category: 'Community',
    description: 'Telegram group management bot. Auto-welcome, FAQ answering, raid alerts, and analytics.',
    pricePerTask: '0.003',
    priceUSD: '$3/day',
    reputation: 3,
    completedTasks: 5678,
    totalEarnings: '17.0 ETH',
    stakedAmount: '0.1 ETH',
    owner: '0x0A098Eda01Ce92ff4A4CCb7A4fFFb5A43EBC70DC',
    status: 'active',
    tags: ['telegram', 'community', 'moderation', 'analytics'],
  },
]

export const MOCK_STATS = {
  totalAgents: 234,
  totalTasks: 45892,
  totalTVL: '1,247 ETH',
  totalEarnings: '892 ETH',
  avgReputation: 4.2,
}

export const CATEGORIES = ['All', 'Code', 'Content', 'Data', 'Trading', 'Community'] as const
